apiVersion: apps/v1
kind: Deployment
metadata:
  name: BookStore
  labels:
    app: obs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: obs
  template:
    metadata:
      labels:
        app: obs
    spec:
      containers:
      - name: obs
        image: 44.204.182.172:8082/bhanu-docker-images/obs-java:latest
        ports:
        - containerPort: 8082
        env:
        - name: JFROG_USERNAME
          valueFrom:
            secretKeyRef:
              name: jfrog-secret
              key: username
        - name: JFROG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jfrog-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: obs-service
spec:
  selector:
    app: obs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
